name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest 
    steps:
    - name: Checkout FriendlyWordsDotNet
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get words files
      run: tools/get-words.sh
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity d --logger "junit;LogFilePath=../../tests/report.xml"
      working-directory: src
    - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'tests/report.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}