name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest 
    steps:
    - name: Checkout FriendlyWordsDotNet
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get words files
      run: |
        tools/get-words.sh
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/FriendlyWordsDotNet
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/FriendlyWordsDotNet
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/FriendlyWordsDotNet
    - name: Upload artifact
    - uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path: src/FriendlyWordsDotNet/bin/Debug/netstandard2.0/