name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest 
    steps:
    - name: Checkout FriendlyWordsDotNet
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Get words files
      run: tools/get-words.sh
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --no-restore
    - name: Set Test Title
      run: |
        echo "title=Test Run ${{github.run_number}}" >> $GITHUB_ENV
        echo "file_name=TestReport.${{github.run_number}}.md" >> $GITHUB_ENV
      working-directory: src
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
      working-directory: src
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Test Run'
        path: ${{github.workspace}}/${{env.file_name}}